// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzRAPyIP78bH0KRDXBN2Od_Ijb-UoxHuU',
    appId: '1:192916983893:web:b0509a42637bd8500b04dc',
    messagingSenderId: '192916983893',
    projectId: 'flutter-iti-b8e23',
    authDomain: 'flutter-iti-b8e23.firebaseapp.com',
    storageBucket: 'flutter-iti-b8e23.firebasestorage.app',
    measurementId: 'G-QTC6D5HJC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7jstAtipeUJOmL8Odb0irxfOhJArs3I',
    appId: '1:192916983893:android:8f27d59271b6836c0b04dc',
    messagingSenderId: '192916983893',
    projectId: 'flutter-iti-b8e23',
    storageBucket: 'flutter-iti-b8e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8CrPRV-QM17vMO0_-8MKiTdmZCtihrsY',
    appId: '1:192916983893:ios:e40ae1738f9328290b04dc',
    messagingSenderId: '192916983893',
    projectId: 'flutter-iti-b8e23',
    storageBucket: 'flutter-iti-b8e23.firebasestorage.app',
    iosBundleId: 'com.example.myCounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8CrPRV-QM17vMO0_-8MKiTdmZCtihrsY',
    appId: '1:192916983893:ios:e40ae1738f9328290b04dc',
    messagingSenderId: '192916983893',
    projectId: 'flutter-iti-b8e23',
    storageBucket: 'flutter-iti-b8e23.firebasestorage.app',
    iosBundleId: 'com.example.myCounterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzRAPyIP78bH0KRDXBN2Od_Ijb-UoxHuU',
    appId: '1:192916983893:web:1342c646a82d10d30b04dc',
    messagingSenderId: '192916983893',
    projectId: 'flutter-iti-b8e23',
    authDomain: 'flutter-iti-b8e23.firebaseapp.com',
    storageBucket: 'flutter-iti-b8e23.firebasestorage.app',
    measurementId: 'G-KKMLX55R1G',
  );
}
